"""user model change for api

Revision ID: 9abba2a4a0cc
Revises: f1defed9ea1b
Create Date: 2022-12-04 12:43:27.487488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abba2a4a0cc'
down_revision = 'f1defed9ea1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
